server:
  port: 8081

spring:
  application:
    name: ms-diners
  # 数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/food?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false
  # Redis
  redis:
    # 启用哨兵模式以后无需直接连接 Redis，通过哨兵可以获得主从信息
    # port: 6379
    # host: 192.168.131.61
    timeout: 3000
    password: 123456
    # 哨兵
    sentinel:
      # 主节点名称
      master: mymaster
      # 主从服务器地址
      nodes: 192.168.131.61:26379,192.168.131.64:26379,192.168.131.65:26379
  # swagger
  swagger:
    base-package: com.sryzzz.diners
    title: 美食社交食客API接口文档

# Oauth2 客户端信息
oauth2:
  client:
    client-id: appId
    secret: 123456
    grant_type: password
    scope: api

# oauth2 服务地址
service:
  name:
    ms-oauth-server: http://ms-oauth2-server/
    ms-points-server: http://ms-points/

# 配置 Eureka Server 注册中心
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka

# Mybatis
mybatis:
  configuration:
    # 开启驼峰映射
    map-underscore-to-camel-case: true

logging:
  pattern:
    console: '%d{HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n'