server:
  port: 8082

spring:
  application:
    name: ms-oauth2-server # 应用名

  # 数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/food?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false
  # Redis
  redis:
    # 启用哨兵模式以后无需直接连接 Redis，通过哨兵可以获得主从信息
    # port: 6379
    # host: 192.168.131.61
    timeout: 3000
    database: 1
    password: 123456
    # 哨兵
    sentinel:
      # 主节点名称
      master: mymaster
      # 主从服务器地址
      nodes: 192.168.131.61:26379,192.168.131.64:26379,192.168.131.65:26379

  # swagger
  swagger:
    base-package: com.sryzzz.oauth2
    title: 美食社交食客API接口文档

# Oauth2
client:
  oauth2:
    client-id: appId # 客户端标识 ID
    secret: 123456 # 客户端安全码
    # 授权类型
    grant_types:
      - password
      - refresh_token
    # token 有效时间，单位秒
    token-validity-time: 2592000
    refresh-token-validity-time: 2592000
    # 客户端访问范围
    scopes:
      - api
      - all

# 配置 Eureka Server 注册中心
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

# Mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰映射

# 指标监控健康检查
management:
  endpoints:
    web:
      exposure:
        include: "*" # 暴露的端点

logging:
  pattern:
    console: '%d{HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n'